<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EV1_Programación_Distribuida</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\Nosotros\" />
    <Folder Include="wwwroot\img\pop Roman\" />
  </ItemGroup>

</Project>
